spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create

customer:
  datasource:
    platform: postgres
    jdbcUrl: jdbc:postgresql://192.168.1.221:5432/app
    username: admin
    password: 123456
    driverClassName: org.postgresql.Driver

employee:
  datasource:
    platform: postgres
    jdbcUrl: jdbc:postgresql://192.168.1.221:5432/cms
    username: admin
    password: 123456
    driverClassName: org.postgresql.Driver

spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults: false

