spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create

customer:
  datasource:
    platform: postgres
    jdbcUrl: jdbc:postgresql://36.33.26.38:5432/app
    username: hfcb
    password: hfcb
    driverClassName: org.postgresql.Driver

employee:
  datasource:
    platform: postgres
    url: jdbc:postgresql://36.33.26.38:5432/cms
    username: hfcb
    password: hfcb
    driver-class-name: org.postgresql.Driver

spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults: false
spring.jpa.properties.hibernate.dialect : org.hibernate.dialect.PostgreSQLDialect
